USE [master]
GO

/****** Object:  Database [tanacsado]    Script Date: 2023. 11. 13. 16:37:33 ******/
CREATE DATABASE [tanacsado]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'tanacsado', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\tanacsado.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'tanacsado_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\tanacsado_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [tanacsado].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [tanacsado] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [tanacsado] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [tanacsado] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [tanacsado] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [tanacsado] SET ARITHABORT OFF 
GO

ALTER DATABASE [tanacsado] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [tanacsado] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [tanacsado] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [tanacsado] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [tanacsado] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [tanacsado] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [tanacsado] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [tanacsado] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [tanacsado] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [tanacsado] SET  ENABLE_BROKER 
GO

ALTER DATABASE [tanacsado] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [tanacsado] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [tanacsado] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [tanacsado] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [tanacsado] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [tanacsado] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [tanacsado] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [tanacsado] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [tanacsado] SET  MULTI_USER 
GO

ALTER DATABASE [tanacsado] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [tanacsado] SET DB_CHAINING OFF 
GO

ALTER DATABASE [tanacsado] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [tanacsado] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [tanacsado] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [tanacsado] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [tanacsado] SET QUERY_STORE = OFF
GO

ALTER DATABASE [tanacsado] SET  READ_WRITE 
GO

