CREATE TABLE ugyfel(
   ugyfel_id INTEGER  NOT NULL PRIMARY KEY 
  ,nev       VARCHAR(30) NOT NULL
  ,telefon   VARCHAR(14)
  ,email     VARCHAR(40)
);
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (1,'Kovács Mariann','(20) 674-21-94','kovacs.mariann@freemail.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (2,'Molnár Lehel','(20) 379-56-48','molnar.lehel@freemail.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (3,'Fazekas Gergely','(30) 581-42-27','fazekasg@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (4,'Kányádi Bálint','(20) 747-43-12','kanyadi.balint@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (5,'Zsolnai György','(70) 162-13-24','zsolnai.gyorgy@forditoiroda.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (6,'Lukács András','(20) 532-29-17','lukacs.andras@freemail.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (7,'Koczka Klaudia','(30) 189-40-52','koczka.klaudia@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (8,'Solymos Judit','(30) 152-59-41','solymosj15@freemail.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (9,'Herczeg Lívia','(70) 217-91-46','herczegl@forditoiroda.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (10,'Nagy Edina','(30) 456-53-20','nagye@forditoiroda.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (11,'Szabó Rita','(20) 498-37-17','szabor@freemail.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (12,'Andrási Mariann','(70) 610-74-27','andrasim@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (13,'Veres Bence','(30) 930-53-31','veres.bence@freemail.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (14,'Guttmann László','(30) 169-37-71','guttmann.laszlo@forditoiroda.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (15,'Kabai Edina','(30) 528-46-11','kabai.edina@freemail.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (16,'Magyar Lívia','(30) 809-96-36','magyarl@forditoiroda.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (17,'Vörös Olga','(30) 305-96-66','voros.olga@freemail.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (18,'Kovács Zsanett','(20) 276-87-24','kovacs.zsanett@freemail.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (19,'Baranyai Eleonóra','(70) 673-32-73','baranyai.eleonora@freemail.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (20,'Verpeléti Gabriella','(20) 553-49-74','verpeleti.gabriella24@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (21,'Kalló Miklós','(70) 749-54-72','kallom@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (22,'Braun Roland','(30) 378-86-32','braunr@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (23,'Jászai Marietta','(20) 978-75-34','jaszai.marietta59@forditoiroda.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (24,'Csiszér Etelka','(20) 578-85-91','csiszer.etelka@forditoiroda.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (25,'Kiss Kitty','(20) 130-62-47','kiss.kitty@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (26,'Zsiday Tímea','(20) 701-29-73','zsiday.timea@freemail.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (27,'Fekete Marietta','(20) 399-10-19','feketem58@forditoiroda.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (28,'Zoltai Roland','(70) 887-87-97','zoltai.roland41@forditoiroda.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (29,'Vörös Etelka','(30) 807-96-92','vorose@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (30,'Verpeléti Fanny','(30) 180-60-52','verpeletif42@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (31,'Kaleczky Lehel','(20) 816-55-74','kaleczkyl@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (32,'Zsiday Zita','(30) 964-36-45','zsidayz@forditoiroda.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (33,'Turai Dávid','(20) 295-87-25','turaid@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (34,'Baranyai Ilona','(20) 705-67-95','baranyai.ilona@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (35,'Molnár István','(30) 432-43-49','molnari@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (36,'Hegyi Dénes','(20) 105-46-82','hegyid56@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (37,'Nyúzó Lídia','(20) 335-85-67','nyuzol@forditoiroda.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (38,'Lukács Adrián','(20) 752-36-19','lukacsa@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (39,'Szűcs Sándor','(20) 590-56-14','szucs.sandor@forditoiroda.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (40,'Koczka Ádám','(30) 207-57-72','koczka.adam@forditoiroda.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (41,'Fazekas Emília','(30) 548-41-52','fazekase@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (42,'Veres Ádám','(20) 363-10-89','veresa@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (43,'Csala Julianna','(20) 870-69-13','csalaj@forditoiroda.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (44,'Madarász Marietta','(30) 586-48-40','madaraszm@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (45,'Keller Zsanett','(70) 294-95-90','kellerz@forditoiroda.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (46,'Gellért Lívia','(30) 642-81-18','gellert.livia@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (47,'Csoó Lídia','(30) 837-54-81','csoo.lidia@forditoiroda.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (48,'Guttmann Fanny','(20) 639-30-96','guttmannf43@forditoiroda.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (49,'Kaleczky Roland','(20) 203-58-72','kaleczky.roland@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (50,'Ambrus Julianna','(20) 174-98-34','ambrus.julianna@forditoiroda.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (51,'Varga Mariann','(20) 469-26-17','varga.mariann@freemail.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (52,'Tolnai Anikó','(30) 716-88-91','tolnaia20@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (53,'Horkai Zita','(70) 833-93-56','horkaiz@freemail.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (54,'Jászai Tamás','(30) 605-30-97','jaszai.tamas@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (55,'Kalló Mariann','(30) 525-86-21','kallo.mariann@freemail.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (56,'Kelemen Emília','(70) 823-30-98','kelemene@forditoiroda.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (57,'Csoó Edina','(30) 966-90-75','csooe38@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (58,'Vörös Sámuel','(30) 170-61-69','voros.samuel@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (59,'Csikós Rita','(20) 266-35-73','csikosr@freemail.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (60,'Kovács Zsanett','(70) 675-16-29','kovacsz@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (61,'Fási Edina','(20) 821-67-22','fasie33@freemail.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (62,'Halmosi Dénes','(70) 776-40-56','halmosid@forditoiroda.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (63,'Lukács Miklós','(70) 114-53-80','lukacs.miklos@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (64,'Szekeres Fanny','(70) 826-20-87','szekeres.fanny@freemail.hu');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (65,'Solymos Géza','(20) 424-42-19','solymosg30@gmail.com');
INSERT INTO ugyfel(ugyfel_id,nev,telefon,email) VALUES (74,'6',NULL,NULL);
